// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cxZftCUlV9uF7TWmboc3oK2XTCyjb6s',
    appId: '1:244431628192:android:04e2129e0269a2ee8466c5',
    messagingSenderId: '244431628192',
    projectId: 'livetalkagora',
    databaseURL: 'https://livetalkagora-default-rtdb.firebaseio.com',
    storageBucket: 'livetalkagora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiSsi2W57C4sH2fNlDFczNJq4CJmKqJk',
    appId: '1:244431628192:ios:b608b6b959f236108466c5',
    messagingSenderId: '244431628192',
    projectId: 'livetalkagora',
    databaseURL: 'https://livetalkagora-default-rtdb.firebaseio.com',
    storageBucket: 'livetalkagora.appspot.com',
    androidClientId: '244431628192-273jiha8jj46je2ec0d4ku88k08fb01s.apps.googleusercontent.com',
    iosClientId: '244431628192-bsmvsua8ig2sm2a3hofjl0chrq6pgljs.apps.googleusercontent.com',
    iosBundleId: 'com.livetalk.randomvideochat',
  );

}